# -*- coding: utf-8 -*-
"""phase 1 mini projectipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvSt735HOfHQJ8z_EaKHcgbqEtqQOmTG
"""

import pandas as pd
import numpy as np
df=pd.read_csv("ecommerce_sales_data.csv")

print(df.describe())

df.info()

df.head()

print(df.isnull().sum())

df[df.duplicated()]
print(df.duplicated().sum())

# Best Selling Product
print("Product Categories:",df["Product Name"].unique())
print("------------------------------------------")
best_category = df.groupby("Product Name")["Quantity"].sum()
print(best_category)
print("----------------------------------------")
print(best_category.sort_values(ascending=False))
print("=========================================")
print("\n")
print("BEST SELLING PRODUCT CATEGORY IS:",best_category.idxmax())

# Monthly Sales Trend Analysis
df["month"]=pd.to_datetime(df["Order Date"]).dt.month_name()
monthly_sales=df.groupby("month")["Sales"].sum()
print(monthly_sales.sort_values(ascending=False))
print("=========================================")
print("\n")
print("Highest Sales in Month:",monthly_sales.idxmax())

# Purchase Pattern Analysis
sale_pattern=df.groupby("Region")["Sales"].sum()
print(sale_pattern.sort_values(ascending=False))
print("\n")
print("Most Purchases from :",sale_pattern.idxmax())

# Revenue Analysis
total_revenue=df["Sales"].sum()
total_profit=df["Profit"].sum()
product_revenue= df.groupby("Product Name")["Sales"].sum()
print(product_revenue.sort_values(ascending=False))
product_profit= df.groupby("Product Name")["Profit"].sum()
print(product_profit.sort_values(ascending=False))
print("\n")
print("Total Revenue:",total_revenue)
print("Total Profit:",total_profit)
print("Most Profitable Product:",product_profit.idxmax())